# Generated by Django 2.0.4 on 2020-06-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=255, verbose_name='商品编号')),
                ('pname', models.CharField(max_length=255, verbose_name='商品名称')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skucode', models.CharField(max_length=255, verbose_name='规格编码')),
                ('code1', models.CharField(max_length=255, verbose_name='规格值1')),
                ('code2', models.CharField(max_length=255, verbose_name='规格值2')),
                ('barcode', models.CharField(max_length=255, verbose_name='条码')),
                ('pnumber', models.CharField(max_length=255, verbose_name='货号')),
                ('weight', models.CharField(max_length=255, verbose_name='重量(kg)')),
                ('longth', models.CharField(max_length=255, verbose_name='长度(cm)')),
                ('width', models.CharField(max_length=255, verbose_name='宽度(cm)')),
                ('heigh', models.CharField(max_length=255, verbose_name='高度(cm)')),
                ('volume', models.CharField(max_length=255, verbose_name='体积(m^3)')),
                ('inventory1', models.CharField(max_length=255, verbose_name='初期库存')),
                ('const1', models.CharField(max_length=255, verbose_name='初期成本价')),
                ('locatcode', models.CharField(max_length=255, verbose_name='货位编码')),
                ('fenlei', models.CharField(max_length=255, verbose_name='分类')),
                ('brand', models.CharField(max_length=255, verbose_name='品牌')),
                ('invoicename', models.CharField(max_length=255, verbose_name='开票名称')),
                ('taxrax', models.CharField(max_length=255, verbose_name='税率')),
                ('price1', models.CharField(max_length=255, verbose_name='标准售价')),
                ('price2', models.CharField(max_length=255, verbose_name='吊牌价')),
                ('price3', models.CharField(max_length=255, verbose_name='批发价')),
                ('price4', models.CharField(max_length=255, verbose_name='参考进价')),
                ('pic1', models.CharField(max_length=255, verbose_name='图片1')),
                ('pic2', models.CharField(max_length=255, verbose_name='图片2')),
                ('pic3', models.CharField(max_length=255, verbose_name='图片3')),
                ('pic4', models.CharField(max_length=255, verbose_name='图片4')),
                ('remarks', models.CharField(max_length=255, verbose_name='备注')),
                ('invendays', models.CharField(max_length=255, verbose_name='消耗周期（天）')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='生产商')),
                ('baozhiqi', models.CharField(max_length=255, verbose_name='保质期（天）')),
                ('purtype', models.CharField(max_length=255, verbose_name='采购类型')),
                ('pcount', models.CharField(max_length=255, verbose_name='数量')),
                ('specifiactions', models.CharField(max_length=255, verbose_name='规格')),
                ('pkind', models.CharField(max_length=255, verbose_name='种类')),
                ('flavor', models.CharField(max_length=255, verbose_name='口味')),
                ('leixing', models.CharField(max_length=255, verbose_name='类型')),
                ('netcontent', models.CharField(max_length=255, verbose_name='净含量')),
                ('texture', models.CharField(max_length=255, verbose_name='材质')),
                ('segnum', models.CharField(max_length=255, verbose_name='段数')),
                ('segment', models.CharField(max_length=255, verbose_name='段位')),
                ('packmeth', models.CharField(max_length=255, verbose_name='包装方式')),
                ('capacity', models.CharField(max_length=255, verbose_name='容量')),
                ('origin', models.CharField(max_length=255, verbose_name='产地')),
                ('vality', models.CharField(max_length=255, verbose_name='有效期')),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Catagory')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
    ]
